const express = require('express');
const mysql = require('mysql');
const cors = require('cors');


const app = express();
const db = mysql.createConnection({
  host: 'localhost',
  database: 'vue_data_table_db',
  user: 'root',
  password: ''
})

const query = (sqlStatement) => 
  new Promise((resolve, reject) => {
    db.query(sqlStatement, (err, results) => {
      if (err)
        return reject(err);
      resolve(results);
    })
  });


app.use(cors({
  origin: 'http://localhost:8080'
}));
app.use(express.json());
app.use(express.urlencoded());

app.get('/', (req, res) => {
  res.send('Hello World');
})


/**
 * this mehtod returns all the records of a given table 
 * @param {string} tableName 
 */
const getAllTableData = (tableName) => 
  async (req, res) => {
    const tableData = await query(`select * from ${tableName}`);
    res.json(tableData);
  }
/**
 * this mehtod returns the tables schema 
 * @param {string} tableName 
 */
const getTableSchema = (tableName) => 
  async (req, res) => {
    const tableSchema = await query(`describe ${tableName}`);
    res.json(tableSchema);
  }
/**
 * this mehtod insertes a new table record filling the ID automatically meaning no need to send the ID with the request
 * @param {string} tableName 
 */
const insertTableRow = (tableName) =>
  async (req, res) => {
    //first value is always the ID which is auto generated by MySQL
    let sqlValuesStatment = '(NULL';
    for (let column in req.body) {
      sqlValuesStatment += `, '${req.body[column]}'`;
    }
    sqlValuesStatment += ')';
    console.log(sqlValuesStatment);
    const insertedTableRow = await query(`insert into ${tableName} values ${sqlValuesStatment}`);
    res.json(insertedTableRow);
  }
/**
 * this mehtod uses the ID from the body of the request object to delete the record in the table 
 * @param {string} tableName 
 */
const deleteTableRow = (tableName) =>
  async (req, res) => {
    const deletedRow = await query(`delete from ${tableName} where id=${req.body.id}`);
    res.json(deletedRow);
  }
/**
 * this mehtod uses the ID from the body of the request object to update the record 
 * @param {string} tableName 
 */
const updateTableRow = (tableName) =>
  async (req, res) => {
    let sqlSetStatment = 'set '
    for (let column in req.body) {
      if (column === 'id') continue;
      sqlSetStatment += `${column} = '${req.body[column]}',`;
    }
    sqlSetStatment = sqlSetStatment.slice(0, -1);

    const updatedRow = await query(`update ${tableName} ${sqlSetStatment} where id=${req.body.id}`);
    res.json(updatedRow);
  }


/**
 * this method creates the basic API template for a given table name using the name as route of the api
 * @param {string} tableName 
 */
const createTableBasicAPI = (tableName) => {
  app.get(`/${tableName}`, getAllTableData(`${tableName}`));
  app.get(`/${tableName}/schema`, getTableSchema(`${tableName}`));
  app.post(`/${tableName}/insert`, insertTableRow(`${tableName}`));
  app.delete(`/${tableName}/delete`, deleteTableRow(`${tableName}`));
  app.patch(`/${tableName}/update`, updateTableRow(`${tableName}`));
}

createTableBasicAPI('users');
createTableBasicAPI('products');




app.listen(3000, () => console.log('Listening at http://localhost:3000/'))